networks:
  inceptionNetwork:
    driver: bridge
volumes:
  wordpress-vol:
  mariadb-vol:

services:
  nginx:
    container_name: nginx
    image: nginx
    build:
      context: ./requirements/nginx/.
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inceptionNetwork
    volumes:
      - wordpress-vol:/var/www/html:ro
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb
    build:
      context: ./requirements/mariadb/.
    networks:
      - inceptionNetwork
    volumes:
      - mariadb-vol:/var/lib/mysql
    env_file:
      - .env
    restart: always
  
  wordpress:
    container_name: wordpress
    image: wordpress
    build:
      context: ./requirements/wordpress/.
    networks:
      - inceptionNetwork
    volumes:
      - wordpress-vol:/var/www/html:rw
      - mariadb-vol:/var/lib/mysql:rw
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
  redis:
    container_name: redis
    image: redis
    build: 
      context: ./requirements/bonus/redis/.
    networks:
      - inceptionNetwork
    volumes:
      - wordpress-vol:/var/www/html:rw
    env_file:
      - .env
    restart: always
  ftp:
    container_name: ftp
    image: ftp
    build:
      context: ./requirements/bonus/ftp/.
    networks:
      - inceptionNetwork
    env_file:
      - .env
    volumes:
      - wordpress-vol:/ftp:rw
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    restart: always


