
networks:
  inception:
    name: inceptionNetwork

services:
  nginx:
    container_name: nginxContainer
    image: nginxImage  # the name of the image of nginx we gonna build
    build:
      context: ./requirements/nginx/. # the location of the dockerfile of nginx
    ports:
      - "443:443"
    env_file:
      - .env

  mariadb:
    container_name: mariadbContainer
    image: mariadbImage
    build:
      context: ./requirements/mariadb/.
    env_file:
      - .env
  
  wordpress:
    container_name: wordpressContainer
    image: wordpressImage
    build:
      context: ./requirements/wordpress/.
    env_file:
      - .env