networks:
  inceptionNetwork:
    driver: bridge
volumes:
  wordpress-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/sajaite/data/wordpress
      o: bind
  mariadb-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/sajaite/data/mariadb
      o: bind
  portainer-vol:
    driver: local
    driver_opts:
      type: none
      device: /home/sajaite/data/portainer
      o: bind

services:
  nginx:
    container_name: nginx
    image: nginx:1337
    build:
      context: ./requirements/nginx/.
    depends_on:
      - wordpress
    ports:
      - "443:443"
    networks:
      - inceptionNetwork
    volumes:
      - wordpress-vol:/var/www/html:ro
    env_file:
      - .env
    restart: always

  mariadb:
    container_name: mariadb
    image: mariadb:1337
    build:
      context: ./requirements/mariadb/.
    networks:
      - inceptionNetwork
    volumes:
      - mariadb-vol:/var/lib/mysql
    env_file:
      - .env
    restart: always
  
  wordpress:
    container_name: wordpress
    image: wordpress:1337
    build:
      context: ./requirements/wordpress/.
    networks:
      - inceptionNetwork
    volumes:
      - wordpress-vol:/var/www/html:rw
      - mariadb-vol:/var/lib/mysql:rw
    env_file:
      - .env
    restart: always
    depends_on:
      - mariadb
  redis:
    container_name: redis
    image: redis:1337
    build: 
      context: ./requirements/bonus/redis/.
    networks:
      - inceptionNetwork
    volumes:
      - wordpress-vol:/var/www/html:rw
    env_file:
      - .env
    restart: always
  ftp:
    container_name: ftp
    image: ftp:1337
    build:
      context: ./requirements/bonus/ftp/.
    networks:
      - inceptionNetwork
    env_file:
      - .env
    volumes:
      - wordpress-vol:/ftp:rw
    ports:
      - "21:21"
      - "21100-21110:21100-21110"
    restart: always
  adminer:
    container_name: adminer
    image: adminer:1337
    build:
      context: ./requirements/bonus/adminer/.
    networks:
      - inceptionNetwork
    restart: always
  app:
    container_name: app
    image: app:1337
    build:
      context: ./requirements/bonus/app/.
    networks:
      - inceptionNetwork
    restart: always
  portainer:
    container_name: portainer
    image: portainer:1337
    build:
      context: ./requirements/bonus/portainer/.
    networks:
      - inceptionNetwork
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - portainer-vol:/data
    restart: always

